language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - node --version
  - rm -rf ./node_modules package-lock.json
  - npm install --no-optional
script:
  - npm test --coverage
  - npm run build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: develop